besocialproject/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    #allow us to connect everything for authorization.
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks')
]

groups/urls.py
from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns = [
    url(r'^$',views.ListGroups.as_view(),name='all'),
    url(r'^new/$',views.CreateGroup.as_view(),name='create'),
    url(r'post/in/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name='single'),


]

posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

groups/models.py
from django.db import models
#allows to use spaces etc for formatting
from django.utils.text import slugify
#for link embedding
import misaka

#gets the user models that's currently active in the project
from django.contrib.auth import get_user_model



#call things off the current user's session
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def__str__(self):
        return self.name

    def save(self,*args,**kwargs):
        #replacing and lowercasing things for the self.name
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    #attributes
    group = model.ForeignKey(Group,related_name='memberships')
    # this comes from the get_user_model
    user = models.ForeignKey(User,related_name='user_group')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import (LoginRequiredMixin, 
                                            PermissionRequiredMixin)
from django.core.urlresolvers import reverse
from django.views import generic
from groups.models import Group, GroupMember

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name', 'decription')
    models = Group


class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    models = Group

groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}

{% comment %} comes from group {% endcomment %}
<h1>{{group.name}}</h1>
<h2>{{group.members.count}}</h2>

<div class="content">
    {% if user in group.members.all %}

        <a href="{%url 'groups:leave' slug=group.slug %}" class='btn btn-lg-fill btn-warning'>Leave Group</a>
    {% else %}
        <a href="{%url 'groups:join' slug=group.slug %}" class='btn btn-lg-fill btn-warning'>Join Group</a>
 

    {% endif %}
</div>
{% endblock %}


{% block group_content %}
<div class="col-md-8">
    {% group.posts.count == 0%}
    <h2>No Post in this Group Yet</h2>
    {%else%}

        
        {% for post in group.posts.all %}
            {% comment %} is like saying extends but the html is injected here {% endcomment %}
            {% include "posts/_post.html" %}

    {% endif %}


{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create a New Group!</h4>
    <form action="{% url 'groups:create'%}" method="post" id='groupForm'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class='btn btn-primary btn-large' value="Create">
    </form>

{% endblock%}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html'%}

{% block pregroup %}
<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>Welcome Back!
        {% comment %} # link to user profil {% endcomment %}
            <a href="{url 'post:for_user' username=user.username %}">
                @{{user.username%}}
            </a>
        </h2>
        {% endif %}

        {% comment %} for every to view {% endcomment %}
        <h2>Groups</h2>
        <p>Welcome to the groups page!</p>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class='btn btn-md btn-fill btn warning'>Create new Group</a>
    {% endif %}
</div>
{% endblock %}


{% block group_content %}
<div class="col-md-8">
    <div class="list-group">
        {% comment %} object list will be a list of groups {% endcomment %}
        {% for group in object_list %}
        <a href="{% url 'groups:single' slug=group.slug%}">
            <h3 class='title list-group-item-heading'>{{group.name}}</h3>
            <div class="list-group-item-text container-fluid">
                {% comment %} allows to use html code were if something is bold for example you will see bold text and not tags {% endcomment %}
                {{group.description_html|safe}}
                <div class="row">
                    <div class="col-md-4">
                        <span class='badge'>{{group.members.count}}</span>
                        member{{group.members.count|pluralize}}
                        <div class="col-md-4">
                            <span class='badge'>{{group.posts.count}}</span>
                            post{{group.posts.count|pluralize}}
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}